
export default new Map([
["src/content/portfolio/golang-anvil.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fportfolio%2Fgolang-anvil.mdx&astroContentModuleFlag=true")],
["src/content/portfolio/golang-flux.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fportfolio%2Fgolang-flux.mdx&astroContentModuleFlag=true")],
["src/content/portfolio/golang-wasabi-cleanup.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fportfolio%2Fgolang-wasabi-cleanup.mdx&astroContentModuleFlag=true")],
["src/content/posts/a-comprehensive-guide-to-major-releases-of-magento-2.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fa-comprehensive-guide-to-major-releases-of-magento-2.mdx&astroContentModuleFlag=true")],
["src/content/posts/butterfly-on-budlea-photograph.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fbutterfly-on-budlea-photograph.mdx&astroContentModuleFlag=true")],
["src/content/posts/plex-media-server-update-in-centos.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fplex-media-server-update-in-centos.mdx&astroContentModuleFlag=true")],
["src/content/posts/rollercoin-intro.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Frollercoin-intro.mdx&astroContentModuleFlag=true")],
["src/content/posts/terraform-installation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fterraform-installation.mdx&astroContentModuleFlag=true")],
["src/content/posts/viewing-disk-space-remaining-in-linux-command-line.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fviewing-disk-space-remaining-in-linux-command-line.mdx&astroContentModuleFlag=true")]]);
		