php:
  risky: false
  version: 7.4
  preset: laravel
  tab-width: 4
  use-tabs: false
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "nova"
      - "nova-components"
      - "storage"
      - "spark"
      - "vendor"
      - "build_local"
      - "build_staging"
      - "public_html"
    name: "*.php"
    not-name:
      - "*.blade.php"
      - "_ide_helper.php"
js: false
ts: false
css: false
vue: false
py: false