# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Composer install jigsaw and all requirements
        uses: php-actions/composer@v5
      - name: Install curl, unzip, rsync and openssh-client
        run: apt-get update && apt-get install -y curl openssh-client rsync unzip
      - name: Install composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - name: Build site files
        run: ./vendor/bin/jigsaw build production
      - name: Rsync to server
        uses: burnett01/rsync-deployments@4.1
          with:
            switches: -avzr --delete
            path: public_html/
            remote_path: /var/www/clivewalkden.co.uk/html/
            remote_host: 35.202.238.191
            remote_user: clivewalkden
            remote_key: ${{ secrets.DEPLOY_KEY }}